[package]
name = "gir"
version = "0.0.1"
authors = [
	"Evgenii Pashkin <eapashkin@gmail.com>",
	"Gleb Kozyrev <gleb@gkoz.com>",
	"Guillaume Gomez <guillaume1.gomez@gmail.com>",
]
build = "build.rs"
exclude = ["Gir*.toml", "tests/**/*", "*.md"]

[dependencies]
docopt = "0.8"
xml-rs = "0.7"
toml = "0.4"
case = "0.1"
env_logger = "0.5"
error-chain = { version = "0.11", default-features = false }
# We can update to newer versions once appveyor has a newer version of libgit
git2 = { version = "=0.6.6", default-features = false }
lazy_static = "1.0"
log = "0.4"
regex = "0.2"
hprof = "0.1"
rustdoc-stripper = { git = "https://github.com/GuillaumeGomez/rustdoc-stripper" }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[build-dependencies]
git2 = { version = "0.6", default-features = false }

[profile.release]
codegen-units = 4
